name: agent_chat_example
description: "Feature showcase app for agent_chat Flutter UI library."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  agent_chat:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: assets/fonts/ALIBABAPUHUITI-2-35-THIN.TTF
          weight: 100
        - asset: assets/fonts/ALIBABAPUHUITI-2-45-LIGHT.TTF
          weight: 300
        - asset: assets/fonts/ALIBABAPUHUITI-2-55-REGULAR.TTF
          weight: 400
        - asset: assets/fonts/ALIBABAPUHUITI-2-65-MEDIUM.TTF
          weight: 500
        - asset: assets/fonts/ALIBABAPUHUITI-2-75-SEMIBOLD.TTF
          weight: 600
        - asset: assets/fonts/ALIBABAPUHUITI-2-85-BOLD.TTF
          weight: 700
        - asset: assets/fonts/ALIBABAPUHUITI-2-95-EXTRABOLD.TTF
          weight: 800
        - asset: assets/fonts/ALIBABAPUHUITI-2-105-HEAVY.TTF
          weight: 900
        - asset: assets/fonts/ALIBABAPUHUITI-2-115-BLACK.TTF
          weight: 900
    - family: KaiTi
      fonts:
        - asset: assets/fonts/simkai.ttf
